### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by xmha97** [Richu-Antony/Calculator_App#1]
Thanks for developing this app.
Please improve landscape mode.

![Screenshot_2023-03-04-07-14-32-517_com rica calculator](https://user-images.githubusercontent.com/23485114/222874276-ccee5b32-96ed-4a9b-b331-f0b64ce2cf7f.jpg)

**Comment by Richu-Antony** [comment]
Minor improvement android:screenOrientation="locked" mode is added to avoid landscape mode rotation
